version: '2'
services:
  mongo:
    image: mongo:3.4
  web:
    build: .
    ports:
     - "3000:3000"
    environment:
     - MONGODB_URI=mongodb://admin:chuber-admin@ds249418.mlab.com:49418/chuber-db-sandbox
    links:
     - mongo
    depends_on:
     - mongo
    volumes:
     - .:/starter
     - /starter/node_modules
     
